### ISSUE TITLE
HTML5 Export only supports WebSocket

### ISSUE THREAD

**Issue by raamweinfeld** [raamweinfeld/Killer-Artists#2]
This might be a problem: https://docs.godotengine.org/en/stable/tutorials/networking/high_level_multiplayer.html

> Most of Godot's supported platforms offer all or most of the mentioned high- and low-level networking features. As networking is always largely hardware and operating system dependent, however, some features may change or not be available on some target platforms. Most notably, the **HTML5 platform currently only offers WebSocket support and lacks some of the higher level features as well as raw access to low-level protocols like TCP and UDP.**

**Comment by Devon7925** [comment]
Should be fine as long as we use websocket.

**Comment by raamweinfeld** [comment]
WebRTC looks like the way to go. Websocket protocol is TCP and too slow for real-time drawing action.
https://docs.godotengine.org/en/stable/tutorials/networking/webrtc.html#doc-webrtc

**Comment by Devon7925** [comment]
https://discord.gg/H33mhNrW

**Comment by Devon7925** [comment]
this is fine now
